=== jsteffo/Programming-web-services/Homework 1/src/xml/company.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="company" xmlns="company" elementFormDefault="qualified">

	<xs:element name="Companies" type="companiesType"/>


	<xs:complexType name="companiesType">
		<xs:sequence>
			<xs:element name="Company" type="companyType" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="companyType">
		<xs:sequence>
			<xs:element name="Office" maxOccurs="unbounded" type="officeType"></xs:element>
		</xs:sequence>
		<xs:attribute name="name" use="required" type="xs:string"></xs:attribute>
		<xs:attribute name="founded" use="required" type="xs:gYear"></xs:attribute>
	</xs:complexType>


	<xs:complexType name="officeType">
		<xs:sequence>
			<xs:element name="Reports" type="reportsType"></xs:element>
		</xs:sequence>
		<xs:attribute name="streetAddress" use="required" type="xs:string"></xs:attribute>
		<xs:attribute name="streetNumber" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minExclusive value="0"></xs:minExclusive>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="workers" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="0"></xs:minInclusive>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>

	</xs:complexType>

	<xs:complexType name="reportsType">
		<xs:sequence>
			<xs:element name="Report" type="reportType" maxOccurs="unbounded">
				
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="reportType" mixed="true">
		<xs:attribute name="type" use="required" type="xs:string"></xs:attribute>
		<xs:attribute name="year" use="required" type="xs:gYear"></xs:attribute>
	</xs:complexType>

</xs:schema>

=== jsteffo/Programming-web-services/Homework 1/src/xml/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<Companies xmlns="company" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="company company.xsd">
	
	<Company name="Ericsson" founded="1877">
		<City name="Stockholm">
			<Office streetAddress="Kistavägen" streetNumber="22" workers="5">
				<Reports>
					<Report type="financial" year="1999">
						This year we sold for phones for 50000kr
					</Report>
					<Report type="financial" year="2000">
						This year we sold phones for 60000 kr
					</Report>
					<Report type="growth" year="1999">
						We expect an increase in sale
					</Report>
					<Report type="growth" year="2000">
						We expect a decrease in sale
					</Report>
				</Reports>
			</Office>
			<Office streetAddress="Drottninggatan" streetNumber="33" workers="45">
				<Reports>
					<Report type="financial" year="1999">
						This year we sold for phones
						for 20000 kr
					</Report>
					<Report type="financial" year="2000">
						This year we sold phones for
						40000 kr
					</Report>
					<Report type="growth" year="1999">
						We expect an increase in sale
					</Report>
					<Report type="growth" year="2000">
						We expect an increase in sale
					</Report>
				</Reports>
			</Office>
		</City>
	</Company>
	<Company name="McDonalds" founded="1877">
		<City name="Lund">
			<Office streetAddress="Storgatan" streetNumber="33" workers="32">
			<Reports>
					<Report type="financial" year="1992">
						This year we sold for burgers
						for 50000 kr
					</Report>
					<Report type="financial" year="2000">
						This year we sold burgers for
						60000 kr
					</Report>
					<Report type="growth" year="1992">
						We expect an increase in sale
					</Report>
					<Report type="growth" year="2003">
						We expect a decrease in sale
					</Report>
				</Reports>
			</Office>
		</City>
		<City name="Stockholm">
			<Office streetAddress="Regeringsgatan" streetNumber="322" workers="65">
				<Reports>
					<Report type="financial" year="1996">
						This year we sold for burgers
						for 20 000 kr
					</Report>
					<Report type="financial" year="2002">
						This year we sold burgers for
						52500 kr
					</Report>
						<Report type="growth" year="1993">
							We expect an increase in sale
						</Report>
						<Report type="growth" year="2006">
							We expect a decrease in sale
						</Report>
					</Reports>
			</Office>
		</City>
	</Company>
	<Company name="Max" founded="1958">
		<City name="Malmö">
			<Office streetAddress="Adelsgatan" streetNumber="4" workers="11">
				<Reports>
					<Report type="financial" year="1995">
						This year we sold for burgers
						for 30 000 kr
					</Report>
					<Report type="financial" year="2004">
						This year we sold burgers for
						64 000 kr
					</Report>
					<Report type="growth" year="1996">
						We expect an increase in sale
					</Report>
					<Report type="growth" year="2005">
						We expect a decrease in sale
					</Report>
				</Reports>
			</Office>
		</City>
	</Company>
</Companies>
